# OpenTelemetry SDK
otel:
  enabled: true
  service_name: "serve"
  service_version: "0.1.2"
  collector:
    endpoint: "" # if not provided, output will be discarded
    protocol: grpc
  attributes:
    environment: dev
  sentry:
    dsn: "" # if not provided, output will be discarded
    environment: dev
    performance_monitoring: true
    traces_sample_rate: 1.0
    profiling_sample_rate: 0.5
# HTTP server
server:
  port: 9090
  cache: 3600
  proxy_protocol: false
  enable_spa: true
  tls:
    enabled: false
    system_ca: true
    cert: /etc/serve/tls/tls.crt
    key: /etc/serve/tls/tls.key
    custom_ca: []
  csp:
    enabled: true
    allow_eval: false
    report_only: true
    report_to:
      - /csp-reports
  middleware:
    gzip: 7
    metadata:
      headers:
        - authorization
        - x-api-key
        - baggage
        - sentry-trace
    otel:
      enabled: true
      trace_header: "x-request-id"
    cors:
      max_age: 300
      options_status_code: 200
      allow_credentials: true
      ignore_options: false
      allowed_headers:
        - authorization
        - content-type
        - x-api-key
        - baggage
        - sentry-trace
      allowed_methods:
        - get
        - head
        - post
        - options
      allowed_origins:
        - "*"
      exposed_headers:
        - authorization
        - x-api-key
        - baggage
        - sentry-trace
