name: publish
env:
  commit_msg: ""
on:
  push:
    tags:
      - "*"
jobs:
  # Publish project package(s)
  publish:
    name: publish package
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      # Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
        # This is required for the changelog to be properly generated
        with:
          fetch-depth: 0

      # Prepare runner environment
      - name: Set up runner environment
        run: ./.github/workflows/assets/utils.sh setup
        env:
          GITHUB_USER: ${{ github.actor }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      # Get commit message
      - name: Get commit message
        run: |
          echo 'commit_msg<<EOF' >> $GITHUB_ENV
          git log --format=%B -n 1 ${{ github.sha }} >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      # Use goreleaser to create the new release
      # https://github.com/goreleaser/goreleaser-action
      - name: Create release
        uses: goreleaser/goreleaser-action@v6
        if: startsWith(github.ref, 'refs/tags/') && !contains(env.commit_msg, '[skip release]')
        with:
          version: latest
          args: release --clean --skip=validate
        env:
          # https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          # Login of the user that initiated the workflow run
          GITHUB_USER: ${{ github.actor }}
